version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - home_server_internal_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - home_server_internal_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - 5601:5601
    networks:
      - home_server_internal_network

  httpd:
    image: httpd:latest
    depends_on:
      - logstash
    ports:
      - 80:80
    logging:
      driver: gelf
      options:
        # Use udp://host.docker.internal:12201 when you are using Docker Desktop for Mac
        # docs: https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
        # issue: https://github.com/lvthillo/docker-elk/issues/1
        gelf-address: "udp://localhost:12201"

networks:
  logging-network:
    driver: bridge
